(deftheme birds-of-paradise
  "Port of the brown-based warm light-on-dark theme by Joe
Bergantine.  Modified significantly by mkmcc, with no attempt at
compatibility.")

(let* ((class '((class color) (min-colors 89)))
       (brown-1  "#452E2E")
       (brown-2  "#865C38")
       (brown-3  "#4B3330")
       (brown-4  "#523D2B")
       (brown-5  "#7D504A")
       (brown-6  "#392626")
       (brown-7  "#3E2929")
       ;;
       (white-1  "#E6E1C4")
       (white-2  "#E6E1DC")
       (white-3  "#654D4D")
       ;;
       (black-1  "#1F1611")
       (black-2  "#16120E")
       (black-3  "#000000")
       (gray-1   "#4e4e4e")
       ;;
       (yellow-1 "#D9D762")
       (yellow-2 "#EFAC32")
       (yellow-3 "#EFCB43")
       (yellow-4 "#EFC232")
       (yellow-5 "#FFC05C")
       ;;
       (orange-1 "#EF5D32")
       (orange-2 "#CC762E")
       (orange-3 "#C74725")
       (red-1    "#990000")
       (red-2    "#660000")
       (red-3    "#CC4232")
       (red-4    "#BE3250")
       (red-5    "#D23850")
       (red-6    "firebrick4")
       (red-7    "#FF7575")
       ;;
       (blue-1   "#7DAF9C")
       (blue-2   "#6C99BB")
       (blue-3   "#5798AE")
       (blue-4   "#93C1BC")
       (blue-5   "#2F33AB")
       (purple-1 "#BB99BB")
       (purple-2 "#8856D2")
       (purple-3 "#BE73FD")
       (green-1  "#144212")
       (green-2  "#8CFF8C")
       ;;
       (bop-fg white-1)
       (bop-bg brown-1))
  (custom-theme-set-faces
   'birds-of-paradise

   ;; Basics
   `(default ((t (:background ,bop-bg :foreground ,bop-fg))))
   `(cursor ((t (:foreground ,brown-2 :background ,bop-fg))))
   `(highlight ((t (:background ,black-1 :foreground ,bop-fg))))
   `(hl-line ((t (:background ,brown-7))))
   `(region ((t (:background ,brown-4))))
   `(escape-glyph ((t (:foreground ,purple-3))))
   `(minibuffer-prompt ((t (:foreground ,blue-2)))) ;todo

   ;; Font-lock stuff
   `(font-lock-builtin-face ((t (:foreground ,blue-2))))
   `(font-lock-constant-face ((t (:foreground ,blue-2))))
   `(font-lock-comment-face ((t (:italic t :foreground ,brown-2))))
   `(font-lock-comment-delimiter-face ((t (:italic t :foreground ,brown-2))))
   `(font-lock-doc-face ((t (:foreground ,brown-2))))
   `(font-lock-doc-string-face ((t (:foreground ,brown-2))))
   `(font-lock-function-name-face ((t (:foreground ,yellow-2))))
   `(font-lock-keyword-face ((t (:foreground ,orange-1))))
   `(font-lock-negation-char-face ((t (:foreground ,blue-1))))
   `(font-lock-preprocessor-face ((t (:foreground ,red-4))))
   `(font-lock-string-face ((t (:foreground ,yellow-1))))
   `(font-lock-type-face ((t (:bold t :foreground ,yellow-2))))
   `(font-lock-variable-name-face ((t (:foreground ,blue-1))))
   `(font-lock-warning-face ((t (:background ,red-1 :foreground "white"))))

   ;; UI related
   `(link ((t (:foreground ,yellow-1))))
   `(button ((t (:foreground ,yellow-1 :background ,blue-1 :weight bold :underline t))))
   `(mode-line ((t (:background ,brown-2 :foreground ,bop-fg))))
   `(mode-line-inactive ((t (:background ,brown-5 :foreground ,bop-fg))))
   `(vertical-border ((t (:foreground ,brown-4))))
   `(fringe ((t (:background ,brown-7 :foreground ,white-3))))

   ;; Linum
   `(linum ((t (:background ,bop-bg :foreground ,white-3))))

   ;; show-paren
   `(show-paren-match ((t (:background ,brown-5))))
   `(show-paren-mismatch ((t (:inherit font-lock-warning-face))))

   ;; ido
   `(ido-only-match ((t (:foreground ,orange-1))))
   `(ido-first-match ((t (:foreground ,red-1))))
   `(ido-subdir ((t (:foreground ,yellow-2))))

   ;; highlight-indentation-mode
   `(highlight-indentation-face ((t (:background ,brown-3))))
   `(highlight-indentation-current-column-face ((t (:background ,brown-4))))

   ;; whitespace-mode
   `(whitespace-empty           ((t (:foreground ,bop-fg  :background ,yellow-2))))
   `(whitespace-hspace          ((t (:foreground ,brown-4 :background ,bop-bg))))
   `(whitespace-indentation     ((t (:foreground ,brown-4 :background ,bop-bg))))
   `(whitespace-line            ((t (:foreground ,bop-fg  :background ,brown-5))))
   `(whitespace-newline         ((t (:foreground ,brown-4 :background ,bop-bg))))
   `(whitespace-space           ((t (:foreground ,brown-4 :background ,bop-bg))))
   `(whitespace-space-after-tab ((t (:foreground ,brown-4 :background ,bop-bg))))
   `(whitespace-tab             ((t (:foreground ,brown-4 :background ,bop-bg))))
   `(whitespace-trailing        ((t (:foreground ,red-3   :background ,bop-bg))))
   `(whitespace-before-tab      ((t (:foreground ,red-3   :background ,bop-bg))))

   ;; flyspell-mode
   `(flyspell-incorrect ((t (:underline ,red-6))))
   `(flyspell-duplicate ((t (:underline ,red-6))))

   ;; magit
   `(magit-diff-add ((t (:foreground ,green-2))))
   `(magit-diff-del ((t (:foreground ,red-7))))
   `(magit-item-highlight ((t (:background ,brown-6))))

   ;; ECB
   `(ecb-default-highlight-face ((t (:background ,red-1))))

   ;; ElScreen
   `(elscreen-tab-background-face ((t (:background ,brown-3))))
   `(elscreen-tab-control-face ((t (:background ,brown-2 :foreground ,bop-fg :underline nil))))
   `(elscreen-tab-current-screen-face ((t (:background ,brown-2 :foreground ,bop-fg))))
   `(elscreen-tab-other-screen-face ((t (:background ,brown-3 :foreground ,bop-fg :underline nil))))

   ;; column-marker-mode
   `(column-marker-1 ((t (:background ,brown-4))))

   ;; isearch
   `(isearch ((t (:foreground ,green-1 :background ,yellow-5))))
   `(isearch-fail ((t (:foreground ,bop-fg :background ,red-1))))
   `(lazy-highlight ((t (:foreground ,bop-fg :background ,blue-1))))

   ;; Misc.
   `(gnus-group-news-1 ((t (:foreground ,yellow-1 :weight bold))))
   `(gnus-group-news-1-empty ((t (:foreground ,yellow-1))))
   `(gnus-group-news-2 ((t (:foreground ,orange-1 :weight bold))))
   `(gnus-group-news-2-empty ((t (:foreground ,orange-1))))
   `(gnus-group-news-3 ((t (:foreground ,red-3 :weight bold))))
   `(gnus-group-news-3-empty ((t (:foreground ,red-3))))
   `(gnus-group-news-4 ((t (:foreground ,purple-1 :weight bold))))
   `(gnus-group-news-4-empty ((t (:foreground ,purple-1))))
   `(gnus-group-news-5 ((t (:foreground ,blue-1 :weight bold))))
   `(gnus-group-news-5-empty ((t (:foreground ,blue-1))))
   `(gnus-group-news-6 ((t (:foreground ,blue-2 :weight bold))))
   `(gnus-group-news-6-empty ((t (:foreground ,blue-2))))
   `(gnus-group-news-low ((t (:foreground ,brown-2 :italic t))))
   `(gnus-group-news-low-empty ((t (:foreground ,brown-2))))
   `(gnus-group-mail-1 ((t (:foreground ,yellow-1 :weight bold))))
   `(gnus-group-mail-1-empty ((t (:foreground ,yellow-1))))
   `(gnus-group-mail-2 ((t (:foreground ,orange-1 :weight bold))))
   `(gnus-group-mail-2-empty ((t (:foreground ,orange-1 :weight bold))))
   `(gnus-group-mail-3 ((t (:foreground ,red-3 :weight bold))))
   `(gnus-group-mail-3-empty ((t (:foreground ,red-3))))
   `(gnus-group-mail-low ((t (:foreground ,brown-2 :italic t))))
   `(gnus-group-mail-low-empty ((t (:foreground ,brown-2))))
   `(gnus-header-content ((t (:weight normal :foreground ,yellow-1))))
   `(gnus-header-from ((t (:foreground ,yellow-1))))
   `(gnus-header-subject ((t (:foreground ,red-3))))
   `(gnus-header-name ((t (:foreground ,blue-2))))
   `(gnus-header-newsgroups ((t (:foreground ,yellow-2))))
   `(gnus-summary-cancelled-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-summary-high-ancient-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-summary-high-read-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-summary-high-ticked-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-summary-high-unread-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-summary-low-ancient-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-summary-low-read-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-summary-low-ticked-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-summary-low-unread-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-summary-normal-ancient-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-summary-normal-read-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-summary-normal-ticked-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-summary-normal-unread-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-summary-selected-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-cite-1-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-cite-10-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-cite-11-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-cite-2-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-cite-3-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-cite-4-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-cite-5-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-cite-6-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-cite-7-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-cite-8-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-cite-9-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-group-news-1-empty-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-group-news-2-empty-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-group-news-3-empty-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-group-news-4-empty-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-group-news-5-empty-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-group-news-6-empty-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-group-news-low-empty-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-signature-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(gnus-x-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-action-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-bold-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-current-nick-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-dangerous-host-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-default-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-direct-msg-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-error-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-fool-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-highlight-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-input-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-keyword-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-nick-default-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-my-nick-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-nick-msg-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-notice-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-pal-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-prompt-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-timestamp-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(erc-underline-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(message-header-name ((t (:foreground ,orange-1))))
   `(message-header-cc ((t (:foreground ,brown-2))))
   `(message-header-other ((t (:foreground ,brown-2))))
   `(message-header-subject ((t (:foreground ,bop-fg))))
   `(message-header-to ((t (:foreground ,bop-fg))))
   `(message-cited-text ((t (:foreground ,yellow-2))))
   `(message-separator ((t (:foreground ,yellow-2))))
   `(nxml-comment-content ((t (:inherit 'font-lock-comment-face))))
   `(nxml-tag-delimiter ((t (:foreground ,yellow-3))))
   `(nxml-processing-instruction-target ((t (:foreground ,brown-2))))
   `(nxml-entity-ref-delimiter ((t (:foreground ,blue-2))))
   `(nxml-entity-ref-name ((t (:foreground ,blue-2))))
   `(nxml-element-local-name ((t (:foreground ,yellow-3))))
   `(nxml-cdata-section-content ((t (:foreground ,red-3))))
   `(nxml-attribute-local-name ((t (:foreground ,orange-1))))
   `(nxml-attribute-value ((t (:foreground ,yellow-1))))

   ;; TODO
   `(c-annotation-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(compilation-column-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(compilation-enter-directory-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(compilation-error-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(compilation-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(compilation-info ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(compilation-info-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(compilation-leave-directory-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(compilation-line-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(compilation-line-number ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(compilation-message-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(compilation-warning-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(diff-added ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(diff-changed ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(diff-file-header ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(diff-header ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(diff-removed ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(escape-glyph-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(eshell-ls-archive ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(eshell-ls-backup ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(eshell-ls-clutter ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(eshell-ls-directory ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(eshell-ls-executable ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(eshell-ls-missing ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(eshell-ls-unreadable ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(grep-context-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(grep-error-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(grep-hit-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(grep-match-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(header-line ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(link-visited ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(match ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(menu ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(secondary-selection ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(eshell-ls-product ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(eshell-ls-special ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(eshell-ls-symlink ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(flymake-errline ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(flymake-warnline ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(magit-section-title ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(magit-branch ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(nav-face-heading ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(nav-face-button-num ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(nav-face-dir ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(nav-face-hdir ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(nav-face-file ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(nav-face-hfile ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(org-agenda-date-today ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(org-archived ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(org-checkbox ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(org-date ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(org-deadline-announce ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(org-done ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(org-formula ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(org-headline-done ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(org-hide ((t (:foreground ,bop-bg :background ,bop-bg))))
   `(org-level-1 ((t (:foreground ,yellow-1 :background ,bop-bg))))
   `(org-level-2 ((t (:foreground ,red-6 :background ,bop-bg))))
   `(org-level-3 ((t (:foreground ,blue-1 :background ,bop-bg))))
   `(org-level-4 ((t (:foreground ,yellow-2 :background ,bop-bg))))
   `(org-level-5 ((t (:foreground ,orange-1 :background ,bop-bg))))
   `(org-level-6 ((t (:foreground ,blue-3 :background ,bop-bg))))
   `(org-level-7 ((t (:foreground ,yellow-4 :background ,bop-bg))))
   `(org-level-8 ((t (:foreground ,purple-3 :background ,bop-bg))))
   `(org-link ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(org-scheduled ((t (:foreground ,blue-3 :background ,bop-bg))))
   `(org-scheduled-previously ((t (:foreground ,blue-1 :background ,bop-bg))))
   `(org-scheduled-today ((t (:foreground ,orange-2 :background ,bop-bg))))
   `(org-special-keyword ((t (:foreground ,red-3 :background ,bop-bg))))
   `(org-table ((t (:foreground ,yellow-1 :background ,bop-bg))))
   `(org-tag ((t (:foreground ,blue-1 :background ,bop-bg))))
   `(org-time-grid ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(org-todo ((t (:foreground ,red-1 :background ,bop-bg))))
   `(org-upcoming-deadline ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(org-warning ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(outline-1 ((t (:foreground ,yellow-1 :background ,bop-bg))))
   `(outline-2 ((t (:foreground ,red-6 :background ,bop-bg))))
   `(outline-3 ((t (:foreground ,blue-1 :background ,bop-bg))))
   `(outline-4 ((t (:foreground ,yellow-2 :background ,bop-bg))))
   `(outline-5 ((t (:foreground ,orange-1 :background ,bop-bg))))
   `(outline-6 ((t (:foreground ,blue-3 :background ,bop-bg))))
   `(outline-7 ((t (:foreground ,yellow-4 :background ,bop-bg))))
   `(outline-8 ((t (:foreground ,purple-3 :background ,bop-bg))))
   `(slime-repl-inputed-output-face ((t (:foreground ,bop-fg :background ,bop-bg))))
   `(which-func ((t (:foreground ,bop-fg :background ,bop-bg)))))

  ;;
  (custom-theme-set-variables
   'birds-of-paradise

   ;; Fill Column Indicator mode
   `(fci-rule-color ,bop-bg) ;; renders much brighter for some reason
   `(fci-rule-character-color ,bop-bg)

   ;; Misc.
   `(ansi-color-names-vector
     ;; black, red, green, yellow, blue, magenta, cyan, white
     [,black-1 ,red-2 ,green-1 ,yellow-4 ,blue-3 ,purple-3 ,blue-4 ,white-2])
   `(ansi-term-color-vector
     ;; [unspecified "black" "red3" "green3" "yellow3" "blue2" "magenta3" "cyan3" "white"]
     [unspecified ,black-1 ,red-2 ,green-1 ,yellow-4 ,blue-3 ,purple-3 ,blue-4 ,white-2])))


;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'birds-of-paradise)
